import { NextResponse, type NextRequest } from "next/server";
import { auth } from "@/features/auth/auth";
import { isPdfBackgroundId } from "@/features/memories/config/pdfBackgrounds";
import { memoryRepository } from "@/features/memories/repository";
import { checkMemoryOutputAccess } from "@/features/memories/services/outputAccess";
import { generateMemoryPdf, MemoryPdfSourceUnavailableError } from "@/features/memories/services/pdf";

/**
 * The only way to read a memory PDF — never a static file URL, and the
 * only place PDF generation is invoked from. Authorization happens
 * entirely server-side here:
 *   - must be signed in,
 *   - must own the project OR be an admin,
 *   - the owner additionally needs the entitlement the shared output
 *     policy (features/memories/lib/outputPolicy.ts) names for this
 *     outputType: a memory_pdf_unlocks row for "personal_pdf", a redeemed
 *     access code for THIS project for "digital_frame", and never for
 *     "physical_gift" or any unknown type. Admins bypass it.
 * See "Digital download security" in CLAUDE.md.
 *
 * `?disposition=inline` renders in-browser (the admin order detail page's
 * "view PDF") instead of forcing a download — same authorization, same
 * generated bytes, just a different Content-Disposition. Never build a
 * second endpoint or a second renderer for "preview" vs "download".
 *
 * `?background=<id>` picks the unframed PDF's design
 * (features/memories/config/pdfBackgrounds.ts). It only changes the
 * artwork: same authorization, still a read that never spends a Token, and
 * ignored for a framed project. Absent → the default design; an id the
 * catalog doesn't list → 400, never a silent fallback.
 */
export async function GET(request: NextRequest, context: { params: Promise<{ projectId: string }> }) {
  // Next.js router fetches (Link prefetch and client-side navigation) are
  // never a real download: the router always sends `rsc: 1`, and prefetches
  // also `next-router-prefetch`/`next-router-segment-prefetch` — headers a
  // browser's own navigation never carries. Answer them before auth or any
  // lookup so they can never trigger the memory-heavy PDF render; on a
  // non-RSC response the router falls back to a normal browser navigation,
  // which then arrives here without these headers and downloads as usual.
  if (
    request.headers.get("rsc") === "1" ||
    request.headers.has("next-router-prefetch") ||
    request.headers.has("next-router-segment-prefetch")
  ) {
    return new NextResponse(null, { status: 204, headers: { "Cache-Control": "private, no-store" } });
  }

  const { projectId } = await context.params;
  const searchParams = new URL(request.url).searchParams;
  const inline = searchParams.get("disposition") === "inline";
  const backgroundId = searchParams.get("background");
  if (backgroundId !== null && !isPdfBackgroundId(backgroundId)) {
    return NextResponse.json({ error: "invalid-background" }, { status: 400 });
  }

  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "auth-required" }, { status: 401 });
  }

  const project = await memoryRepository.getById(projectId);
  if (!project) {
    return NextResponse.json({ error: "not-found" }, { status: 404 });
  }

  // Owner + per-outputType entitlement, deny by default — see
  // features/memories/lib/outputPolicy.ts. Read-only: this GET never spends
  // a token; unlocking (and paying) happens only in `unlockMemoryPdf`.
  const access = await checkMemoryOutputAccess(project, session.user, "pdf", { adminBypass: true });
  if (!access.allowed) {
    return NextResponse.json({ error: access.reason }, { status: 403 });
  }

  try {
    const pdf = await generateMemoryPdf(project, { backgroundId });
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `${inline ? "inline" : "attachment"}; filename="mindot-memory-${project.id.slice(0, 8)}.pdf"`,
        "Cache-Control": "private, no-store",
      },
    });
  } catch (error) {
    if (error instanceof MemoryPdfSourceUnavailableError) {
      return NextResponse.json({ error: "source-unavailable" }, { status: 410 });
    }
    throw error;
  }
}
