import { NextResponse, type NextRequest } from "next/server";
import { auth } from "@/features/auth/auth";
import { digitalAccessCodeRepository, memoryRepository } from "@/features/memories/repository";
import { generateMemoryPdf, MemoryPdfSourceUnavailableError } from "@/features/memories/services/pdf";

/**
 * The only way to read a memory PDF — never a static file URL, and the
 * only place PDF generation is invoked from. Authorization happens
 * entirely server-side here:
 *   - must be signed in,
 *   - must own the project OR be an admin,
 *   - a "digital_frame" project additionally requires a redeemed access
 *     code for THIS project specifically (not just any valid code).
 * See "Digital download security" in CLAUDE.md.
 *
 * `?disposition=inline` renders in-browser (the admin order detail page's
 * "view PDF") instead of forcing a download — same authorization, same
 * generated bytes, just a different Content-Disposition. Never build a
 * second endpoint or a second renderer for "preview" vs "download".
 */
export async function GET(request: NextRequest, context: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await context.params;
  const inline = new URL(request.url).searchParams.get("disposition") === "inline";

  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "auth-required" }, { status: 401 });
  }

  const project = await memoryRepository.getById(projectId);
  if (!project) {
    return NextResponse.json({ error: "not-found" }, { status: 404 });
  }

  const isAdmin = session.user.role === "admin";
  const isOwner = project.createdBy === session.user.id;
  if (!isAdmin && !isOwner) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  if (!isAdmin && project.outputType === "digital_frame") {
    const hasAccess = await digitalAccessCodeRepository.hasRedeemedCodeForProject(project.id);
    if (!hasAccess) {
      return NextResponse.json({ error: "access-not-redeemed" }, { status: 403 });
    }
  }

  try {
    const pdf = await generateMemoryPdf(project);
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `${inline ? "inline" : "attachment"}; filename="mindot-memory-${project.id.slice(0, 8)}.pdf"`,
        "Cache-Control": "private, no-store",
      },
    });
  } catch (error) {
    if (error instanceof MemoryPdfSourceUnavailableError) {
      return NextResponse.json({ error: "source-unavailable" }, { status: 410 });
    }
    throw error;
  }
}
