import { getAuthRuntimeConfig } from "@/lib/env";
import { appleTokenRepository } from "../appleTokenRepository";

const APPLE_REVOKE_URL = "https://appleid.apple.com/auth/revoke";
const REVOKE_TIMEOUT_MS = 10_000;

/**
 * The outcome of trying to end an account's Sign in with Apple
 * authorization before deleting it:
 *   - `revoked`: Apple confirmed the revocation (HTTP 200).
 *   - `nothing-to-revoke`: nothing Apple still honors — no stored token
 *     (e.g. an account from before tokens were stored), or Apple answered
 *     `invalid_grant` (the token is already revoked/expired).
 *   - `not-configured`: Apple sign-in is switched off on this deployment
 *     (no client secret/key), so no revocation can be attempted.
 *   - `unreadable`: a token is stored but no longer decrypts (key rotated).
 *   - `failed`: Apple was unreachable, errored, or rejected our client
 *     secret (e.g. an expired AUTH_APPLE_SECRET) — fixable, so the caller
 *     keeps the account and asks the user to retry.
 */
export type AppleRevokeOutcome = "revoked" | "nothing-to-revoke" | "not-configured" | "unreadable" | "failed";

/**
 * One call to Apple's revoke endpoint, authenticated with the same
 * client-secret JWT sign-in uses (AUTH_APPLE_SECRET, generated by
 * `npm run auth:apple-secret`). Logs only an outcome category and HTTP
 * status — never the token or the secret. `fetchImpl` exists for tests.
 */
export async function revokeAppleRefreshToken(
  refreshToken: string,
  credentials: { clientId: string; clientSecret: string },
  fetchImpl: typeof fetch = fetch
): Promise<"revoked" | "nothing-to-revoke" | "failed"> {
  let response: Response;
  try {
    response = await fetchImpl(APPLE_REVOKE_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: credentials.clientId,
        client_secret: credentials.clientSecret,
        token: refreshToken,
        token_type_hint: "refresh_token",
      }),
      signal: AbortSignal.timeout(REVOKE_TIMEOUT_MS),
    });
  } catch (error) {
    console.error("[apple-revoke] request failed", error instanceof Error ? error.name : "unknown");
    return "failed";
  }
  if (response.ok) return "revoked";

  const error = await response
    .json()
    .then((body: unknown) => (typeof body === "object" && body !== null && "error" in body ? String((body as { error: unknown }).error) : ""))
    .catch(() => "");
  if (error === "invalid_grant") return "nothing-to-revoke";
  console.error("[apple-revoke] rejected", response.status, error || "no-error-code");
  return "failed";
}

/**
 * Revokes the web Apple authorization stored for this (Apple) account. Only
 * the `"web"` token: it is the one AUTH_APPLE_ID/AUTH_APPLE_SECRET (the
 * Services ID) can revoke. An `"ios"` token belongs to the app's bundle ID
 * and needs that client's own credentials — not handled here yet.
 */
export async function revokeAppleAuthorizationForUser(userId: string, fetchImpl: typeof fetch = fetch): Promise<AppleRevokeOutcome> {
  const config = getAuthRuntimeConfig();
  if (!config.appleId || !config.appleSecret || !config.appleTokenKey) return "not-configured";

  const stored = await appleTokenRepository.read(userId, "web", config.appleTokenKey);
  if (stored === "none") return "nothing-to-revoke";
  if (stored === "unreadable") return "unreadable";
  return revokeAppleRefreshToken(stored, { clientId: config.appleId, clientSecret: config.appleSecret }, fetchImpl);
}
